---

###############################################################################
# Domain and hostname information
network:
  domain: sample.do
  hostname: blog.sample.do

##############################################################################
# Extra security values
security:
  auto_update: true
  app_armor: true
  mod_security:
    install: true

###############################################################################
# Drupal settings
drupal:
  subdomain: blog
  site_name: My wonderful life

###############################################################################
# System related
system:
  release: stretch
  ssl: letsencrypt
  devel: false
  debug: true

